### ISSUE TITLE
the performance is not as good as you described in your papers? if there are any other key point?

### ISSUE THREAD

**Issue by maliho0803** [Prinsphield/ELEGANT#13]
I use your code train the celeba datasets with Attributes of bangs and mustache, I get very bad results/

**Comment by Prinsphield** [comment]
Make sure that your training images are cropped and aligned as described [here](https://github.com/Prinsphield/ELEGANT/blob/master/README.md#training-on-celeba-dataset) and follow the other instructions as well.

**Comment by maliho0803** [comment]
Thank you very much for your reply!

I have followed all your tips. I will show you my training results, please help me to find out what happened.
 









I am look forward to your advices after you check my results, thank you again!

**Comment by Prinsphield** [comment]
You can reach me via email.
