### ISSUE TITLE
preprocess.py

### ISSUE THREAD

**Issue by maliho0803** [Prinsphield/ELEGANT#14]
when using preprocess.py to crop image, if the size must be 409 x 687?

**Comment by Prinsphield** [comment]
No. Different images are of different size. The size of the first image is 409 x 687 if you are using the same dataset.

**Comment by maliho0803** [comment]
if the size of input image is too small, it will get wrong results?

**Comment by Prinsphield** [comment]
Of course. You can check the images after processing.
