### ISSUE TITLE
is there any pre-trained models

### ISSUE THREAD

**Issue by gaoyangyiqiao** [Prinsphield/ELEGANT#4]
The data for training is large. Is there a pre-trained model?

**Comment by Prinsphield** [comment]
The celeba dataset is less than 5 GB, which is not very large.
I do not provide pre-trained model.

**Comment by Prinsphield** [comment]
The tar file of cropped and aligned images is less than 5gb, but the original one is much larger. 
I have provided the `preprocess.py` for preprocessing the original images. So you might have to download the original celeba dataset. Sorry!

**Comment by gaoyangyiqiao** [comment]
Thanks a lot.
