### ISSUE TITLE
What is the number of dimentions of latent space?

### ISSUE THREAD

**Issue by YusukeO** [Prinsphield/ELEGANT#6]
Is the number of dimentions of latent space 40? (equal to the number of celebA attributes)

**Comment by Prinsphield** [comment]
No. The latent representations of an image is a tensor of shape `8 * 8 * 512`, as you can find in the [`net.py`](https://github.com/Prinsphield/ELEGANT/blob/d78608ec11fe9377206ed71d5e372983c2f35e72/nets.py#L30-L59)

**Comment by YusukeO** [comment]
Thank you for your quick reply.
Then, I have another question.
When we specify just two attributes (Bangs and Mustache), how do you split the latent representations of shape 8 * 8 * 512? 
From my understanding of your paper, former 8*8*256 part is for Bangs and 8*8*256 for Mustache. Is it correct?

**Comment by Prinsphield** [comment]
Split the tensor `8 * 8 * 512` into two tensors of shape `8 * 8 * 256`.

**Comment by YusukeO** [comment]
Thank you so much!
