### ISSUE TITLE
Get many many noises on C and D

### ISSUE THREAD

**Issue by phelogges** [Prinsphield/ELEGANT#7]
Thanks for your elegant work!
I'm implementing your paper by TF, but there comes many noises when I sample from outputs and it's getting worse...
I'm not sure if it happens to model collapse or something else...
I trained model on a subset of celebA with 10000 images. 
The number on images is iterations with batch size 2.
Hope for your advice, thanks!
![noise](https://github.com/phelogges/For-Link/blob/master/noise.jpeg)

**Comment by Prinsphield** [comment]
Could you please share me a private repo, so that I can check your code?

**Comment by phelogges** [comment]
[Here](https://github.com/phelogges/ELEGANT_TF) is my code
Thanks!

**Comment by Prinsphield** [comment]
Hello, good Implementation! 

There are several differences or mistakes in your code.
- **[difference]** The multi-scale discriminators share parameters. They are of identical network structure, but with difference input image scale. However, in your implementation, they have seperate parameters. 
- **[mistake]**  The strategy of training ELEGANT is iterative training: for each iteration, we train ELEGANT with respect to one attribute. For example, if training with respect to the `smiling` attribute, the input data should be a batch of smiling images (`A`), and another batch of non-smiling images (`B`). Either `A` or `B` cannot be a random batch images. I believe you misunderstand this part. You can refer to [dataset.py](https://github.com/Prinsphield/ELEGANT/blob/master/dataset.py) and [here](https://github.com/Prinsphield/ELEGANT/blob/caee3df5e63a74cecf80293b97dfc1f6d400f982/ELEGANT.py#L281) for knowing more about how to feed the input data as well as the iterative training strategy.
