### ISSUE TITLE
How do you define interpolation matrix with 4 images as inputs?

### ISSUE THREAD

**Issue by YusukeO** [Prinsphield/ELEGANT#8]
Hi, again.

I wonder how you define interpolation matrix with 4 images as inputs when you make the matrix according to 1 attribute.
I think 3 images are enough and necessary to determine linear interpolation sphere, but you seem to input 4 images (including base image).
So my question is what is your strategy to make the matrix with 4 inputs.

Thanks!

**Comment by Prinsphield** [comment]
As you can see [here](https://github.com/Prinsphield/ELEGANT#3-matrix-interpolation-with-respect-to-one-attribute), the upper-left image is the input image that has no Bangs, whereas the other three are reference bangs images. In order do interpolation on the image space, you only need to do interpolation in the latent space.  Please refer to the [code](https://github.com/Prinsphield/ELEGANT/blob/master/ELEGANT.py#L365-L398) for details.

**Comment by YusukeO** [comment]
Is no Bangs or Bangs matter?
No-Bangs image also has bang-latent space, doesn't it?

So, now we have 4 points in bang-latent space. 
We consider a sphere on 3 points in bang-latent space (upper-left, upper-right, and bottom-left). 
I understand we can make a matrix in the sphere which is defined by the 3 points.
But what is the bottom-right image? This image may not be on the sphere.

**Comment by Prinsphield** [comment]
Yeah, you can swap latent representations of two bangs images.

The latent space is not a 2-d space. 

As for the interpolation, four images contribute to the interpolation image together with different weight on the latent encodings, where the weight of certain one encoding is higher if the interpolation image is more close to that corresponding image.

**Comment by YusukeO** [comment]
Now, I perfectly understood.

Thank you for your quick and rich reply!
