### ISSUE TITLE
How to align face without landmark gt?

### ISSUE THREAD

**Issue by HrsPythonix** [Prinsphield/ELEGANT#9]
The faces in Celeba has landmark gt, I see you use them to align the face in preprocess.py. But how do you align faces without landmark gt, for example, how do you deal with the faces in images dir? What algorithm do you use for landmark detection?

Thanks ~

**Comment by HrsPythonix** [comment]
By the way, I am training the model using only the Smiling attribute,  trained on two 1080 and batch size is changed to 32, how should I know when the model converges and stop training?

**Comment by HrsPythonix** [comment]
![image](https://user-images.githubusercontent.com/16586180/47834511-ba1ef480-ddda-11e8-89f1-c0143478defd.png)
![image](https://user-images.githubusercontent.com/16586180/47834524-c5722000-ddda-11e8-8054-c4448628106e.png)

**Comment by Prinsphield** [comment]
Any open source face alignment should be okay. [Here](https://github.com/1adrianb/face-alignment) is the one for your reference. 

Watch images in your tensorboard. If it is well trained, then the generated images should be good.

**Comment by HrsPythonix** [comment]
Thanks for your reply, I use [https://github.com/ageitgey/face_recognition](this) to detect landmark, and it returns dict as below:

{'nose_bridge': [(118L, 115L), (115L, 130L), (112L, 147L), (108L, 162L)], 'left_eye': [(85L, 106L), (92L, 101L), (102L, 103L), (109L, 113L), (100L, 114L), (90L, 112L)], 'nose_tip': [(103L, 167L), (108L, 173L), (115L, 175L), (124L, 173L), (133L, 170L)], 'chin': [(78L, 111L), (75L, 129L), (75L, 147L), (82L, 165L), (89L, 183L), (97L, 201L), (103L, 219L), (111L, 237L), (125L, 245L), (145L, 244L), (170L, 235L), (192L, 221L), (214L, 204L), (228L, 184L), (236L, 160L), (240L, 134L), (243L, 109L)], 'right_eye': [(148L, 117L), (157L, 109L), (169L, 109L), (178L, 116L), (169L, 120L), (158L, 120L)], 'left_eyebrow': [(73L, 86L), (79L, 80L), (88L, 84L), (98L, 90L), (107L, 97L)], 'bottom_lip': [(168L, 187L), (151L, 205L), (133L, 212L), (122L, 212L), (113L, 210L), (106L, 201L), (103L, 183L), (107L, 186L), (114L, 199L), (122L, 201L), (132L, 202L), (164L, 189L)], 'right_eyebrow': [(133L, 98L), (152L, 93L), (169L, 90L), (187L, 93L), (201L, 102L)], 'top_lip': [(103L, 183L), (107L, 182L), (114L, 183L), (121L, 185L), (131L, 184L), (149L, 185L), (168L, 187L), (164L, 189L), (131L, 189L), (121L, 189L), (114L, 187L), (107L, 186L)]}

And I refer to the list_landmark_celeba.txt:

lefteye_x lefteye_y righteye_x righteye_y nose_x nose_y leftmouth_x leftmouth_y rightmouth_x rightmouth_y
000001.jpg 165  184  244  176  196  249  194  271  266  260

How do I get the corresponding x and y from the dict?

**Comment by Prinsphield** [comment]
You can plot all these points in a face image, and choose the 5 points in the face images: two center points of eyes, the center point of nose, and two corner points of the mouth. Once you know which 5 points that you need, you can apply to other images

**Comment by HrsPythonix** [comment]
Thanks!
